version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 18
    commands:
      - pip install --upgrade awscli
      - aws s3 cp s3://bucketsai/kops /usr/local/bin/kops
      - chmod +x /usr/local/bin/kops
  build:
    commands:
      - kops version
      - echo "sample" >> /usr/rt.log
